"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

const texts = {
  en: {
    home: "Home",
    brandName: "Revesty",
    searchPlaceholder: "Search items...",
    browse: "Browse",
    sell: "Sell",
    login: "Login",
    signup: "Sign Up",
    favorites: "Favorites",
    cart: "Cart",
    myListings: "My Listings",
    account: "Account",
    inbox: "Inbox",
    preferences: "Preferences",
    back: "Back",
    view: "View",
    save: "Save changes",
    saved: "Saved successfully!",
    favoritesTitle: "Your Favorites",
    cartTitle: "Your Cart",
    emptyCart: "Your cart is empty.",
    emptyFavorites: "You don't have favorite items yet.",
    continueShopping: "Continue shopping",
    removeFromCart: "Remove",
    removeFromFavorites: "Remove",
    total: "Total",
    checkout: "Checkout",
    checkoutTitle: "Checkout",
    checkoutSubtitle: "Complete your order details below.",
    orderSummary: "Order summary",
    orderSuccess: "Your order was placed successfully!",
    orderEmpty: "You need items in your cart to checkout.",
    fullName: "Full name",
    firstName: "First name",
    lastName: "Last name",
    address: "Address",
    city: "City",
    country: "Country",
    shippingAddress: "Shipping address",
    billingAddress: "Billing address",
    useDifferentBilling: "Use a different billing address",
    sameAsShipping: "Billing address is the same as shipping address",
    paymentMethod: "Payment method",
    cardNumber: "Card number",
    cardName: "Name on card",
    expiryDate: "Expiry date",
    cvv: "CVV",
    placeOrder: "Place order",
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to your Revesty account",
    email: "Email",
    password: "Password",
    loginButton: "Login",
    noAccount: "Don't have an account?",
    createAccount: "Create account",
    signupTitle: "Create your account",
    signupSubtitle: "Join Revesty and start selling today",
    name: "Name",
    signupButton: "Sign Up",
    haveAccount: "Already have an account?",
    signIn: "Sign in",
    profileTitle: "My Account",
    profileSubtitle: "Manage your personal profile and seller information.",
    profilePhoto: "Profile photo URL",
    bio: "Bio",
    cityLabel: "City",
    countryLabel: "Country",
    stats: "Your summary",
    publishedItems: "Published items",
    favoriteItems: "Favorite items",
    cartItems: "Cart items",
    messageSeller: "Message seller",
    writeMessage: "Write your message...",
    sendMessage: "Send message",
    inboxTitle: "Inbox",
    inboxSubtitle: "Your conversations with sellers.",
    noMessages: "No messages yet.",
    buyerLabel: "You",
    sellerLabel: "Seller",
    replyHere: "Reply here...",
    price: "Price",
    brand: "Brand",
    size: "Size",
    category: "Category",
    condition: "Condition",
    addToCart: "Add to cart",
    addToFavorites: "Add to favorites",
    productTitle: "Product title",
    description: "Description",
    publish: "Publish item",
    uploadPhoto: "Upload photo",
    imageUrl: "Image URL",
    heroTag: "FASHION MARKETPLACE",
    heroTitle: "Revesty",
    heroSubtitle:
      "Buy and sell clothes, shoes, bags and accessories in good or excellent condition.",
    sellItem: "Sell Item",
    browseItems: "Browse Items",
    browseTitle: "Browse Items",
    browseSubtitle: "Discover fashion pieces you'll love",
    all: "All",
    clothes: "Clothes",
    shoes: "Shoes",
    bags: "Bags",
    accessories: "Accessories",
    notifications: "Notifications",
    marketingEmails: "Marketing emails",
    privateProfile: "Private profile",
    notificationsDescription: "Receive visual updates inside the app.",
    marketingDescription: "Receive news and offers by email.",
    privateProfileDescription: "Hide some public profile information.",
    preferencesTitle: "Preferences",
    preferencesSubtitle: "Manage your app settings and personal preferences.",
    languageSetting: "Language"
  },
  es: {
    home: "Inicio",
    brandName: "Revesty",
    searchPlaceholder: "Buscar artículos...",
    browse: "Explorar",
    sell: "Vender",
    login: "Entrar",
    signup: "Crear cuenta",
    favorites: "Favoritos",
    cart: "Carrito",
    myListings: "Mis artículos",
    account: "Cuenta",
    inbox: "Inbox",
    preferences: "Preferencias",
    back: "Atrás",
    view: "Ver",
    save: "Guardar cambios",
    saved: "¡Guardado con éxito!",
    favoritesTitle: "Tus favoritos",
    cartTitle: "Tu carrito",
    emptyCart: "Tu carrito está vacío.",
    emptyFavorites: "Todavía no tienes artículos favoritos.",
    continueShopping: "Seguir comprando",
    removeFromCart: "Quitar",
    removeFromFavorites: "Quitar",
    total: "Total",
    checkout: "Pagar",
    checkoutTitle: "Pago",
    checkoutSubtitle: "Completa los datos de tu pedido aquí.",
    orderSummary: "Resumen del pedido",
    orderSuccess: "¡Tu compra fue realizada con éxito!",
    orderEmpty: "Necesitas productos en tu carrito para pagar.",
    fullName: "Nombre completo",
    firstName: "Nombre",
    lastName: "Apellido",
    address: "Dirección",
    city: "Ciudad",
    country: "País",
    shippingAddress: "Dirección de envío",
    billingAddress: "Dirección de facturación",
    useDifferentBilling: "Usar una dirección de facturación diferente",
    sameAsShipping: "La dirección de facturación es la misma que la de envío",
    paymentMethod: "Método de pago",
    cardNumber: "Número de tarjeta",
    cardName: "Nombre en la tarjeta",
    expiryDate: "Fecha de vencimiento",
    cvv: "CVV",
    placeOrder: "Confirmar compra",
    loginTitle: "Bienvenida de nuevo",
    loginSubtitle: "Inicia sesión en tu cuenta de Revesty",
    email: "Correo electrónico",
    password: "Contraseña",
    loginButton: "Entrar",
    noAccount: "¿No tienes una cuenta?",
    createAccount: "Crear cuenta",
    signupTitle: "Crea tu cuenta",
    signupSubtitle: "Únete a Revesty y empieza a vender hoy",
    name: "Nombre",
    signupButton: "Crear cuenta",
    haveAccount: "¿Ya tienes una cuenta?",
    signIn: "Inicia sesión",
    profileTitle: "Mi cuenta",
    profileSubtitle: "Administra tu perfil personal y tu información de vendedora.",
    profilePhoto: "URL de foto de perfil",
    bio: "Biografía",
    cityLabel: "Ciudad",
    countryLabel: "País",
    stats: "Tu resumen",
    publishedItems: "Artículos publicados",
    favoriteItems: "Favoritos",
    cartItems: "Artículos en carrito",
    messageSeller: "Mensaje al vendedor",
    writeMessage: "Escribe tu mensaje...",
    sendMessage: "Enviar mensaje",
    inboxTitle: "Inbox",
    inboxSubtitle: "Tus conversaciones con vendedores.",
    noMessages: "Todavía no hay mensajes.",
    buyerLabel: "Tú",
    sellerLabel: "Vendedor",
    replyHere: "Responde aquí...",
    price: "Precio",
    brand: "Marca",
    size: "Talla",
    category: "Categoría",
    condition: "Estado",
    addToCart: "Agregar al carrito",
    addToFavorites: "Agregar a favoritos",
    productTitle: "Título del producto",
    description: "Descripción",
    publish: "Publicar artículo",
    uploadPhoto: "Subir foto",
    imageUrl: "URL de la imagen",
    heroTag: "MARKETPLACE DE MODA",
    heroTitle: "Revesty",
    heroSubtitle:
      "Compra y vende ropa, zapatos, bolsos y accesorios en buen o excelente estado.",
    sellItem: "Vender artículo",
    browseItems: "Explorar artículos",
    browseTitle: "Explorar artículos",
    browseSubtitle: "Descubre piezas de moda que te encantarán",
    all: "Todo",
    clothes: "Ropa",
    shoes: "Zapatos",
    bags: "Bolsos",
    accessories: "Accesorios",
    notifications: "Notificaciones",
    marketingEmails: "Correos de marketing",
    privateProfile: "Perfil privado",
    notificationsDescription: "Recibe avisos visuales dentro de la app.",
    marketingDescription: "Recibe noticias y ofertas por correo.",
    privateProfileDescription: "Oculta parte de la información pública de tu perfil.",
    preferencesTitle: "Preferencias",
    preferencesSubtitle: "Administra la configuración de la app y tus preferencias personales.",
    languageSetting: "Idioma"
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("en");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("revesty-language");
    if (savedLanguage === "en" || savedLanguage === "es") {
      setLanguage(savedLanguage);
      document.documentElement.lang = savedLanguage;
    }
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem("revesty-language", lang);
    document.documentElement.lang = lang;
  };

  const value = useMemo(() => {
    return {
      language,
      changeLanguage,
      t: texts[language] || texts.en
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}